name: CodeIgniter CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: codeigniter_db
          MYSQL_USER: ci_user
          MYSQL_PASSWORD: ci_password
          MYSQL_ROOT_PASSWORD: root_password
        ports:
          - 3306:3306

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          extensions: mbstring, mysqli, pdo, pdo_mysql

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Setup .env file
        run: cp env .env

      - name: Run migrations
        run: php spark migrate

      - name: Run tests
        run: vendor/bin/phpunit
